### ISSUE TITLE
Is it possible to search for duplicates line only in selection?

### ISSUE THREAD

**Issue by 9840380** [LordBrom/HighlightDuplicates#16]

**Comment by 9840380** [comment]
It would be very cool if you added an additional option only in the selected text
And option to select all duplicate lines, after the first instance.

**Comment by LordBrom** [comment]
> It would be very cool if you added an additional option only in the selected text

I think I understand but just to make sure. You are wanting to be able to select a subset of the current file, and have the plugin only "look" at lines that have content selected? I think I can add that. I'll add an option to enable it, so it maintains current functionality. It will probably also only affect the Select/Remove Duplicate commands.

> And option to select all duplicate lines, after the first instance.

I am not sure what you mean by this one though.

**Comment by 9840380** [comment]
> I think I understand but just to make sure. You are wanting to be able to select a subset of the current file, and have the plugin only "look" at lines that have content selected? I think I can add that. I'll add an option to enable it, so it maintains current functionality. It will probably also only affect the Select/Remove Duplicate commands.

Yep:
**Select Duplicates only in selected text  from the file** 
**Remove Duplicates only in selected text  from the file**

**Comment by 9840380** [comment]
>> And option to select all duplicate lines, after the first instance.
>I am not sure what you mean by this one though.

**Selected Duplicates only in selected text after the first instance**
Using this command will select all duplicate lines  in selected text, after the first instance, from the file.
_This is useful to see what will be removed before manual removal._

**Comment by 9840380** [comment]
**+Additional option** 

Option to ignore the line in selection when there is nothing after the cursor (Ignore empty selection in line)
Or ideally an option where you can write a regular expression or expressions to ignore the line when matching

**Comment by LordBrom** [comment]
I have created v1.7.0, it should be coming at you soon. It just includes the "using selected text" update, and I really like how it turned out, thank you for the suggestion!

As for the other suggestions, it seems the first is just the same as the built in command "find_all_under", which I believe is defaulted to "alt+f3". Additionally, the Highlight Duplicate command Remove Duplicates should keep the first instance of each duplicate set it is removing. So, using "find_all_under", and then "remove_duplicates", sounds like what you are trying to achieve. 

There is already settings to ignore lines, though I don't think it can use RegEx. I can look into adding a specifically RegEx ignore option, if that is what you are looking for.

**Comment by gitressa** [comment]
Thanks for an awesome tool @LordBrom, it works really well. Is it the new feature here, which is mentioned in the README under https://github.com/LordBrom/HighlightDuplicates#use-selection?

HighlightDuplicates also works well in Sublime Text 4, perhaps it can be added here?

- https://packagecontrol.io/packages/Highlight%20Duplicates
- https://github.com/LordBrom/HighlightDuplicates

Also, I see other Packages such as PlainTasks include Key Bindings ... perhaps it could be considered?
